package com.yejh.dao;

import com.yejh.bean.Key;
import com.yejh.bean.KeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int countByExample(KeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int deleteByExample(KeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int insert(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int insertSelective(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    List<Key> selectByExample(KeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    Key selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Key record, @Param("example") KeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByExample(@Param("record") Key record, @Param("example") KeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByPrimaryKeySelective(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_key
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByPrimaryKey(Key record);
}