package com.yejh.dao;

import com.yejh.bean.Lock;
import com.yejh.bean.LockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int countByExample(LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int deleteByExample(LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int insert(Lock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int insertSelective(Lock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    List<Lock> selectByExample(LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    Lock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Lock record, @Param("example") LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByExample(@Param("record") Lock record, @Param("example") LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByPrimaryKeySelective(Lock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_lock
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    int updateByPrimaryKey(Lock record);
}