package com.yejh.bean;

public class Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_key.id
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_key.keyName
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    private String keyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_key.lockId
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    private Integer lockid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_key.id
     *
     * @return the value of t_key.id
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_key.id
     *
     * @param id the value for t_key.id
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_key.keyName
     *
     * @return the value of t_key.keyName
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    public String getKeyname() {
        return keyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_key.keyName
     *
     * @param keyname the value for t_key.keyName
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    public void setKeyname(String keyname) {
        this.keyname = keyname == null ? null : keyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_key.lockId
     *
     * @return the value of t_key.lockId
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    public Integer getLockid() {
        return lockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_key.lockId
     *
     * @param lockid the value for t_key.lockId
     *
     * @mbggenerated Wed Dec 18 19:45:22 CST 2019
     */
    public void setLockid(Integer lockid) {
        this.lockid = lockid;
    }
}